export const IS_AUTH = 'IS_AUTH'
export const USER_LOGGED = 'USER_LOGGED'
export const DATA_CONSULTATION = 'DATA_CONSULTATION'
export const SINGLE_CONSULTATION = 'SINGLE_CONSULTATION'
export const ENUM_STATUS = {
    PRESCRIBE: "PRESCRIBE",
    ESCALATE: "ESCALATE"
}